name: 'repostat'
description: 'Installs repostat and runs it on the repository, generating HTML reports.'
author: 'Lot49 Cybernetics'

branding:
  icon: 'award'
  color: 'black'

inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
